language: python
git:
  depth: 2
python:
  # - 3.5
  - 3.6
branches:
  only:
  - master
  - dev/main
script:
  - pytest --cov=app --cov-report=xml
install:
  - "pip install --upgrade pip"
  - "pip install pipenv"
  - "pipenv install --dev"
  - "pip install codecov"
  - "pip install pytest"
  - "pip install pytest-sugar"
  - "pip install pytest-cov"
  - "pip install numpy"
  - "pip install pandas"
  - "pip install requests"
after_success:
    - codecov
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - yarn build
